webtalk_init -webtalk_dir C:/Users/Luiz/Desktop/Projeto de circuitos integrados digitais/Projeto Final/processador_6_instrucoes/processador_6_instrucoes.sim/sim_1/behav/xsim/xsim.dir/tb_processador_6_instrucoes_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr  7 04:54:57 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212253514_0_0_148" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e6af1d58-ad6e-4ef6-8fa1-bc1085161c16" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "71e51cb56bb34c09a4374b21dc3a2f1a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "25" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "88 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "21 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "38" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "23" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.73_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "70488_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1083110194 -regid "212253514_0_0_148" -xml C:/Users/Luiz/Desktop/Projeto de circuitos integrados digitais/Projeto Final/processador_6_instrucoes/processador_6_instrucoes.sim/sim_1/behav/xsim/xsim.dir/tb_processador_6_instrucoes_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Luiz/Desktop/Projeto de circuitos integrados digitais/Projeto Final/processador_6_instrucoes/processador_6_instrucoes.sim/sim_1/behav/xsim/xsim.dir/tb_processador_6_instrucoes_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Luiz/Desktop/Projeto de circuitos integrados digitais/Projeto Final/processador_6_instrucoes/processador_6_instrucoes.sim/sim_1/behav/xsim/xsim.dir/tb_processador_6_instrucoes_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
