@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Apr 07 04:54:50 -0300 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 71e51cb56bb34c09a4374b21dc3a2f1a --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_processador_6_instrucoes_behav xil_defaultlib.tb_processador_6_instrucoes -log elaborate.log"
call xelab  -wto 71e51cb56bb34c09a4374b21dc3a2f1a --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_processador_6_instrucoes_behav xil_defaultlib.tb_processador_6_instrucoes -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
